# Server
server.port=8080

# PostgreSQL (NEON)
spring.datasource.url=jdbc:postgresql://ep-sparkling-silence-aogg8vxl.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OaAgSnsZ2v4M
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson: serialize LocalDate properly
spring.jackson.serialization.write-dates-as-timestamps=false
